include: [component: $CI_SERVER_FQDN/lc-components/id_tokens/id_tokens-component@main]

variables:
  LLNL_SERVICE_USER: "weaveci"

stages:
  - setup
  - build_tools_docs
  - build_weave_docs
  - deploy

.on_blueos3_gpu_cz:
  tags:
    - shell
    - lassen

.on_blueos3_gpu_rz:
  variables:
    PARTITION: "pdebug"
  tags:
    - shell
    - rzansel

.on_blueos3_gpu_scf:
  tags:
    - shell
    - sierra

.run_on_cz:
  rules:
    - if: $SOURCE_ZONE == "CZ" && $CI_PIPELINE_SOURCE != "merge_request_event"
 
.run_on_rz:
  rules:
    - if: $SOURCE_ZONE == "RZ" && $CI_PIPELINE_SOURCE != "merge_request_event"

.run_on_scf:
  rules:
    - if: $SOURCE_ZONE == "SCF" && $CI_PIPELINE_SOURCE != "merge_request_event"    

.do_setup:
  stage: setup
  script:
    - make setup
    
.build_ibis_docs:
  stage: build_tools_docs
  script:
    - make build_ibis_docs

.build_kosh_docs:
  stage: build_tools_docs
  script:
    - make build_kosh_docs

.build_maestrowf_docs:
  stage: build_tools_docs
  script:
    - make build_maestrowf_docs

.build_merlin_docs:
  stage: build_tools_docs
  script:
    - make build_merlin_docs

.build_pydv_docs:
  stage: build_tools_docs
  script:
    - make build_pydv_docs

.build_sina_docs:
  stage: build_tools_docs
  script:
    - make build_sina_docs

.build_trata_docs:
  stage: build_tools_docs
  script:
    - make build_trata_docs

.build_weave_docs:
  stage: build_weave_docs
  script:
    - make build_weave_docs

.deploy:
  stage: deploy
  script:
    - make deploy_docs

#
# CZ
#   
setup_cz:
  extends: [ .on_blueos3_gpu_cz, .run_on_cz, .do_setup ]
  artifacts:
    paths:
      - docs
      - weave_ci

build_ibis_docs_cz:
  needs: [ setup_cz ]
  extends: [ .on_blueos3_gpu_cz, .run_on_cz, .build_ibis_docs ]
  artifacts:
    paths:
      - docs
      - weave_ci
    
build_kosh_docs_cz:
  needs: [ setup_cz ]
  extends: [ .on_blueos3_gpu_cz, .run_on_cz, .build_kosh_docs ]

build_maestrowf_docs_cz:
  needs: [ setup_cz ]
  extends: [ .on_blueos3_gpu_cz, .run_on_cz, .build_maestrowf_docs ]

build_merlin_docs_cz:
  needs: [ setup_cz ]
  extends: [ .on_blueos3_gpu_cz, .run_on_cz, .build_merlin_docs ]

build_pydv_docs_cz:
  needs: [ setup_cz ]
  extends: [ .on_blueos3_gpu_cz, .run_on_cz, .build_pydv_docs ]

build_sina_docs_cz:
  needs: [ setup_cz ]
  extends: [ .on_blueos3_gpu_cz, .run_on_cz, .build_sina_docs ]

build_trata_docs_cz:
  needs: [ setup_cz ]
  extends: [ .on_blueos3_gpu_cz, .run_on_cz, .build_trata_docs ]

build_weave_docs_cz:
  needs: [ build_ibis_docs_cz, build_kosh_docs_cz, build_maestrowf_docs_cz, build_merlin_docs_cz, build_pydv_docs_cz, build_sina_docs_cz, build_trata_docs_cz ]
  extends: [ .on_blueos3_gpu_cz, .run_on_cz, .build_weave_docs ]
  artifacts:
    paths:
      - docs

deploy_docs_cz:
  needs: [ build_weave_docs_cz ]
  extends: [ .on_blueos3_gpu_cz, .run_on_cz, .deploy ]

#
# RZ
#          
setup_rz:
  extends: [ .on_blueos3_gpu_rz, .run_on_rz, .do_setup ]
  artifacts:
    paths:
      - docs
      - weave_ci

build_ibis_docs_rz:
  needs: [ setup_rz ]
  extends: [ .on_blueos3_gpu_rz, .run_on_rz, .build_ibis_docs ]
  artifacts:
    paths:
      - docs
      - weave_ci
    
build_kosh_docs_rz:
  needs: [ setup_rz ]
  extends: [ .on_blueos3_gpu_rz, .run_on_rz, .build_kosh_docs ]

build_maestrowf_docs_rz:
  needs: [ setup_rz ]
  extends: [ .on_blueos3_gpu_rz, .run_on_rz, .build_maestrowf_docs ]

build_merlin_docs_rz:
  needs: [ setup_rz ]
  extends: [ .on_blueos3_gpu_rz, .run_on_rz, .build_merlin_docs ]

build_pydv_docs_rz:
  needs: [ setup_rz ]
  extends: [ .on_blueos3_gpu_rz, .run_on_rz, .build_pydv_docs ]

build_sina_docs_rz:
  needs: [ setup_rz ]
  extends: [ .on_blueos3_gpu_rz, .run_on_rz, .build_sina_docs ]

build_trata_docs_rz:
  needs: [ setup_rz ]
  extends: [ .on_blueos3_gpu_rz, .run_on_rz, .build_trata_docs ]


build_weave_docs_rz:
  needs: [ build_ibis_docs_rz, build_kosh_docs_rz, build_maestrowf_docs_rz, build_merlin_docs_rz, build_pydv_docs_rz, build_sina_docs_rz, build_trata_docs_rz ]
  extends: [ .on_blueos3_gpu_rz, .run_on_rz, .build_weave_docs ]
  artifacts:
    paths:
      - docs
    
deploy_docs_rz:
  needs: [ build_weave_docs_rz ]
  extends: [ .on_blueos3_gpu_rz, .run_on_rz, .deploy ]
 

#
# SCF
#
setup_scf:
  extends: [ .on_blueos3_gpu_scf, .run_on_scf, .do_setup ]
  artifacts:
    paths:
      - docs
      - weave_ci

build_ibis_docs_scf:
  needs: [ setup_scf ]
  extends: [ .on_blueos3_gpu_scf, .run_on_scf, .build_ibis_docs ]
  artifacts:
    paths:
      - docs
      - weave_ci
    
build_kosh_docs_scf:
  needs: [ setup_scf ]
  extends: [ .on_blueos3_gpu_scf, .run_on_scf, .build_kosh_docs ]

build_maestrowf_docs_scf:
  needs: [ setup_scf ]
  extends: [ .on_blueos3_gpu_scf, .run_on_scf, .build_maestrowf_docs ]

build_merlin_docs_scf:
  needs: [ setup_scf ]
  extends: [ .on_blueos3_gpu_scf, .run_on_scf, .build_merlin_docs ]

build_pydv_docs_scf:
  needs: [ setup_scf ]
  extends: [ .on_blueos3_gpu_scf, .run_on_scf, .build_pydv_docs ]

build_sina_docs_scf:
  needs: [ setup_scf ]
  extends: [ .on_blueos3_gpu_scf, .run_on_scf, .build_sina_docs ]

build_trata_docs_scf:
  needs: [ setup_scf ]
  extends: [ .on_blueos3_gpu_scf, .run_on_scf, .build_trata_docs ]

build_weave_docs_scf:
  needs: [ build_ibis_docs_scf, build_kosh_docs_scf, build_maestrowf_docs_scf, build_merlin_docs_scf, build_pydv_docs_scf, build_sina_docs_scf, build_trata_docs_scf ]
  extends: [ .on_blueos3_gpu_scf, .run_on_scf, .build_weave_docs ]
  artifacts:
    paths:
      - docs
    
deploy_docs_scf:
  needs: [ build_weave_docs_scf ]
  extends: [ .on_blueos3_gpu_scf, .run_on_scf, .deploy ]

